spring:
  application:
    name: yu-ai-agent
  profiles:
    active: local
  data:
    redis:
      host: 127.0.0.1      # Redis 服务器地址 (本地为 127.0.0.1)
      port: 6379           # Redis 端口号 (默认 6379)
      password:            # Redis 密码（无密码留空）
      database: 0          # 默认使用 0 号库
      timeout: 5000ms      # 连接超时时间
      lettuce:
        pool:
          max-active: 100  # 高并发下的最大连接数 (核心配置)
          max-wait: -1ms   # 连接池耗尽时无限等待
          max-idle: 10     # 最大空闲连接
          min-idle: 2      # 最小空闲连接
  datasource:
#    url: jdbc:postgresql://pgm-bp1osy9424y2g39vxo.pg.rds.aliyuncs.com:5432/yu_ai_agent
#    username: Action_Squad
#    password: Zx777111!
#    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://127.0.0.1:3306/yu_ai_agent?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      # 需要替换为你自己的 key
      api-key: sk-1287df1e0e73482e8cc64590f909e41f
      chat:
        options:
          model: qwen-plus
# 临时注释掉，便于大家开发调试和部署（实际需要启动 MCP 服务）
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
# 临时注释掉，便于大家开发调试和部署（实际需要启动 PgVector 数据库）
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    vectorstore:
      milvus:
        client:
          host: localhost      # 你的 Milvus 运行地址 (如果是 Docker 就是 localhost)
          port: 19530          # Milvus 默认的 gRPC 通信端口
        # 核心表结构配置
        collection-name: love_master_knowledge  # 集合名称 (表名)
        embedding-dimension: 1536               # 向量维度 (非常关键！)
        index-type: HNSW                        # 索引算法
        metric-type: COSINE                     # 距离度量算法
        initialize-schema: true                 # 允许 Spring 自动建表
# Redisson 配置
redisson:
  threads: 16
  nettyThreads: 32
  single-server-config:
    address: "redis://127.0.0.1:6379"
    password:              # 明确设置为空，无密码认证
    database: 0
    connection-minimum-idle-size: 5
    connection-pool-size: 10
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境中打印日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除的值
      logic-not-delete-value: 0 # 逻辑未删除的值
# 在最外层或自定义一个节点
yu-ai:
  memory:
    # 数据库拉取历史消息的安全上限
    safe-limit: 20

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  # 需要替换为你自己的 key
  api-key: sqdvuLWErbwrfJe4rfgK9o1G
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG
